import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import "./globals.css";
import {
  ArrowUpTrayIcon,
  HomeIcon,
  MagnifyingGlassIcon,
} from "@heroicons/react/20/solid";
import { UserIcon } from "@heroicons/react/24/solid";
import { UserCircleIcon } from "@heroicons/react/24/outline";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function rootLayout({
  children,
  layoutProps, //Propriedade true or false para dizer se o layout vai ser renderizado ou não
}: {
  children: React.ReactNode;
  layoutProps: boolean;
}) {
  if (layoutProps == true) {
    // Depedendo de qual página tiver mudar o icone de acordo com a página
    return (
      <html lang="pt-br">
        <body className={inter.className}>
          {children}
          <div className="sticky bottom-0 flex justify-around bg-white p-1">
            <Link href="/home">
              <HomeIcon className="w-10 text-black" />
            </Link>

            <Link href="/search">
              <MagnifyingGlassIcon className="w-10 text-black" />
            </Link>

            <Link href="/upload">
              <ArrowUpTrayIcon className="w-10 text-black" />
            </Link>

            <Link href="/profile" style={{ color: "white" }}>
              <UserCircleIcon className="w-10 text-black" />
            </Link>
          </div>
        </body>
      </html>
    );
    //Children é a página que vai ser renderizada, no caso o layout ele renderiza por cima da página em questão
  } else {
    return (
      <html>
        <body>{children}</body>
      </html>
    );
  }
}
